---
- name: 2.1 | Ensure that the --cert-file and --key-file arguments are set as appropriate (Scored)
  shell: ps -ef | grep etcd
  # --cert-file and the --key-file arguments are set as appropriate
  tags:
    - "2.1"
    - "scored"
    - "level_1"

- name: 2.2 | Ensure that the --client-cert-auth argument is set to true (Scored)
  shell: ps -ef | grep etcd
  # --client-cert-auth argument is set to true
  tags:
    - "2.2"
    - "scored"
    - "level_1"

- name: 2.3 | Ensure that the --auto-tls argument is not set to true (Scored)
  shell: "ps -ef | grep etcd"
  # --auto-tls argument exists, it is not set to true, e.g. --auto-tls=false
  tags:
    - "2.3"
    - "scored"
    - "level_1"

- name: 2.4 | Ensure that the --peer-cert-file and --peer-key-file arguments are set as appropriate (Scored)
  shell: "ps -ef | grep etcd"
  # --peer-cert-file and --peer-key-file arguments are set as appropriate
  tags:
    - "2.4"
    - "scored"
    - "level_1"

- name: 2.5 | Ensure that the --peer-client-cert-auth argument is set to true (Scored)
  shell: "ps -ef | grep etcd"
  # --peer-client-cert-auth argument is set to true
  tags:
    - "2.5"
    - "scored"
    - "level_1"

- name: 2.6 | Ensure that the --peer-auto-tls argument is not set to true (Scored)
  shell: "ps -ef | grep etcd"
  # --peer-auto-tls argument exists, it is not set to true, e.g. --peer-auto-tls=false
  tags:
    - "2.6"
    - "scored"
    - "level_1"

- name: 2.7 | Ensure that a unique Certificate Authority is used for etcd (Not Scored)
  shell: "ps -ef | grep etcd"
  # file referenced by the --client-ca-file for apiserver is different from the --trusted-ca-file used by etcd
  tags:
    - "2.7"
    - "not_scored"
    - "level_2"
