- name: 2.1 | Ensure that the --cert-file and --key-file arguments are set as appropriate (Scored)
  tags:
    - ""

- name: 2.2 | Ensure that the --client-cert-auth argument is set to true (Scored)
  tags:
    - ""

- name: 2.3 | Ensure that the --auto-tls argument is not set to true (Scored)
  tags:
    - ""

- name: 2.4 | Ensure that the --peer-cert-file and --peer-key-file arguments are set as appropriate (Scored)
  tags:
    - ""

- name: 2.5 | Ensure that the --peer-client-cert-auth argument is set to true (Scored)
  tags:
    - ""

- name: 2.6 | Ensure that the --peer-auto-tls argument is not set to true (Scored)
  tags:
    - ""

- name: 2.7 | Ensure that a unique Certificate Authority is used for etcd (Not Scored)
  tags:
    - ""
