---
- name: 3.1.1 | Client certificate authentication should not be used for users (Not Scored)
  shell: "echo 'ensure that users are not making use of Kubernetes client certificate authentication'"
  tags:
    - "3"
    - "not_scored"
    - "level_2"

- name: 3.2.1 | Ensure that a minimal audit policy is created (Scored)
  shell: "ps -ef | grep kube-apiserver"
  # --audit-policy-file is set and is valid policy
  tags:
    - "3"
    - "scored"
    - "level_1"

- name: 3.2.2 | Ensure that the audit policy covers key security concerns (Not Scored)
  shell: ""
  # Audit - only log metadata for requests to Secrets, ConfigMaps, and TokenReviews, modification of Pod and Deployment objects
  # Audit - log metadate of use of pods/exec , pods/portforward , pods/proxy and services/proxy
  tags:
    - "3"
    - "not_scored"
    - "level_2"
