- name: 3.1.1 | Client certificate authentication should not be used for users (Not Scored)
  tags:
    - ""

- name: 3.2.1 | Ensure that a minimal audit policy is created (Scored)
  tags:
    - ""

- name: 3.2.2 | Ensure that the audit policy covers key security concerns (Not Scored)
  tags:
    - ""
