---
- name: 5.1.1 | Ensure that the cluster-admin role is only used where required (Not Scored)
  tags:
    - ""

- name: 5.1.2 | Minimize access to secrets (Not Scored)
  tags:
    - ""

- name: 5.1.3 | Minimize wildcard use in Roles and ClusterRoles (Not Scored)
  tags:
    - ""

- name: 5.1.4 | Minimize access to create pods (Not Scored)
  tags:
    - ""

- name: 5.1.5 | Ensure that default service accounts are not actively used. (Scored)
  tags:
    - ""

- name: 5.1.6 | Ensure that Service Account Tokens are only mounted where necessary (Not Scored)
  tags:
    - ""

- name: 5.2.1 | Minimize the admission of privileged containers (Not Scored)
  tags:
    - ""

- name: 5.2.2 | Minimize the admission of containers wishing to share the host process ID namespace (Scored)
  tags:
    - ""

- name: 5.2.3 | Minimize the admission of containers wishing to share the host IPC namespace (Scored)
  tags:
    - ""

- name: 5.2.4 | Minimize the admission of containers wishing to share the host network namespace (Scored)
  tags:
    - ""

- name: 5.2.5 | Minimize the admission of containers with allowPrivilegeEscalation (Scored)
  tags:
    - ""

- name: 5.2.6 | Minimize the admission of root containers (Not Scored)
  tags:
    - ""

- name: 5.2.7 | Minimize the admission of containers with the NET_RAW capability (Not Scored)
  tags:
    - ""

- name: 5.2.8 | Minimize the admission of containers with added capabilities (Not Scored)
  tags:
    - ""

- name: 5.2.9 | Minimize the admission of containers with capabilities assigned (Not Scored)
  tags:
    - ""

- name: 5.3.1 | Ensure that the CNI in use supports Network Policies (Not Scored)
  tags:
    - ""

- name: 5.3.2 | Ensure that all Namespaces have Network Policies defined (Scored)
  tags:
    - ""

- name: 5.4.1 | Prefer using secrets as files over secrets as environment variables (Not Scored)
  tags:
    - ""

- name: 5.4.2 | Consider external secret storage (Not Scored)
  tags:
    - ""

- name: 5.5.1 | Configure Image Provenance using ImagePolicyWebhook admission controller (Not Scored)
  tags:
    - ""

- name: 5.7.1 | Create administrative boundaries between resources using namespaces (Not Scored)
  tags:
    - ""

- name: 5.7.2 | Ensure that the seccomp profile is set to docker/default in your pod definitions (Not Scored)
  tags:
    - ""

- name: 5.7.3 | Apply Security Context to Your Pods and Containers (Not Scored)
  tags:
    - ""

- name: 5.7.4 | The default namespace should not be used (Scored)
  tags:
    - ""
